package edu.wpi.teamW;

import edu.wpi.teamW.dB.*;
import edu.wpi.teamW.dB.enums.Languages;
import edu.wpi.teamW.frontEnd.LanguageInterpreterServiceRequestController;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Objects;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

/**
 * The main API class that contains all methods for accesing the Language Interpreter Service
 * Request API
 */
public class API {

  /** List of requests generated by the user */
  public static ArrayList<LanguageRequest> reqList = new ArrayList<>();

  // Loads the database whenever API class is called
  static {
    DBController.getDBController();
  }

  private static Stage stage;

  /**
   * Get all Language Requests created by the user after the API has ran
   *
   * @return a list of LanguageRequests
   */
  public static ArrayList<LanguageRequest> getAllRequests() {
    return reqList;
  }

  /**
   * Get a list of all employees in the database
   *
   * @return A list of all employees in the database
   * @throws SQLException if the query to the database failed
   */
  public static ArrayList<Employee> getAllEmployees() throws SQLException {
    return EmployeeManager.getEmployeeManager().getAllEmployees();
  }

  /**
   * Wipes all employees from the database
   *
   * @throws Exception if the employees failed to be deleted
   */
  public static void deleteAllEmployees() throws Exception {
    try {
      ArrayList<Employee> e = EmployeeManager.getEmployeeManager().getAllEmployees();

      for (Employee employee : e) {
        LanguageInterpreterManager.getLanguageInterpreterManager()
            .deleteLanguageInterpsFromEmployeeID(employee.getEmployeeID());
        EmployeeManager.getEmployeeManager().deleteEmployee(employee.getEmployeeID());
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  /**
   * Updates an employees name in the database
   *
   * @param employeeID The ID(Integer) of the employee to update
   * @param newFirstName The new first name of the employee (pass current first name to keep the
   *     same)
   * @param newLastName The new last name of the employee (pass current last name to keep the same)
   * @throws SQLException
   */
  public static void changeEmployeeName(Integer employeeID, String newFirstName, String newLastName)
      throws SQLException {
    Employee e = new Employee(employeeID, newFirstName, newLastName);
    EmployeeManager.getEmployeeManager().changeEmployee(e);
  }

  /**
   * Delete an employee from the database
   *
   * @param employee The employee to delete
   * @throws Exception if the employee failed to be deleted
   */
  public static void deleteEmployee(Employee employee) throws Exception {
    LanguageInterpreterManager.getLanguageInterpreterManager()
        .deleteLanguageInterpsFromEmployeeID(employee.getEmployeeID());
    EmployeeManager.getEmployeeManager().deleteEmployee(employee.getEmployeeID());
  }

  /**
   * Add a new language to an employee
   *
   * @param employee the employee to add a language to
   * @param language the language to add to the employee
   * @throws SQLException
   */
  public static void setEmployeeLanguage(Employee employee, Languages language)
      throws SQLException {
    LanguageInterpreter lI =
        new LanguageInterpreter(employee.getEmployeeID(), language.getString());
    LanguageInterpreterManager.getLanguageInterpreterManager().addLanguageInterpreter(lI);
  }

  /**
   * Add an employee to the database without adding a language to it
   *
   * @param employee the employee to add to the database
   * @throws SQLException
   */
  public static void addEmployeeWithoutLanguage(Employee employee) throws SQLException {
    EmployeeManager.getEmployeeManager().addEmployee(employee);
  }

  /**
   * Add an employee to the database and the language that the employee speaks
   *
   * @param employee the employee to be added to the database
   * @param language the language to be added to the employee
   * @throws SQLException
   */
  public static void addEmployeeWithLanguage(Employee employee, Languages language)
      throws SQLException {
    EmployeeManager.getEmployeeManager().addEmployee(employee);
    LanguageInterpreter lI =
        new LanguageInterpreter(employee.getEmployeeID(), language.getString());
    LanguageInterpreterManager.getLanguageInterpreterManager().addLanguageInterpreter(lI);
  }

  /**
   * Runs the Language Interpreter Service Request Page
   *
   * @param xCoord The x-coordinate for the window to be created at (0 is fully left)
   * @param yCoord The y-coordinate for the window to be created at (0 is fully up)
   * @param windowWidth The width of the window (if width and height are 0, opens in fullscreen)
   * @param windowLength The height of the window (if width and height are 0, opens in fullscreen)
   * @param cssPath The path of the css file
   * @param destLocationID The destination that requests should be completed at
   * @param originLocationID The destination that requests should be completed at
   * @throws ServiceException
   */
  public static void run(
      int xCoord,
      int yCoord,
      int windowWidth,
      int windowLength,
      String cssPath,
      String destLocationID,
      String originLocationID)
      throws ServiceException {

    FXMLLoader root =
        new FXMLLoader(
            Main.class.getResource(
                "/edu/wpi/teamW/views/" + "LanguageInterpreterServiceRequestPage.fxml"));

    AnchorPane mainScene = null;
    try {
      mainScene = (AnchorPane) root.load();
    } catch (IOException e) {
      e.printStackTrace();
      throw (new ServiceException());
    }

    LanguageInterpreterServiceRequestController langController =
        (LanguageInterpreterServiceRequestController) root.getController();
    langController.setLocation(destLocationID);

    Scene scene = new Scene(mainScene, (double) windowWidth, (double) windowLength);
    scene
        .getStylesheets()
        .add(((URL) Objects.requireNonNull(Main.class.getResource(cssPath))).toExternalForm());
    scene.getStylesheets().add(App.class.getResource(cssPath).toExternalForm());

    stage = new Stage();
    stage.setScene(scene);
    stage.setX((double) xCoord);
    stage.setY((double) yCoord);
    if (windowWidth == 0 && windowLength == 0) {
      stage.setFullScreen(true);
    }
    stage.setWidth((double) windowWidth);
    stage.setHeight((double) windowLength);
    stage.show();
  }

  /** closes the App, and exports database to CSVs */
  public static void closeApp() {
    stage.close();
  }

  /** Export all CSVS from the database */
  public static void exportCSVs() {
    LanguageManager.getLanguageManager().exportLocationsCSV("NewLanguageCSV.csv");
    LanguageInterpreterManager.getLanguageInterpreterManager()
        .exportReqCSV("NewLanguageInterpCSV.csv");
    EmployeeManager.getEmployeeManager().exportEmpCSV("NewEmployeeCSV.csv");
  }
}
